# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rq3Rr1gliHj6DCxivQvbaNYXh3F_rGwp
"""

# --- 1. Define the Neural Network Architecture ---
class DQN(nn.Module):
    """A simple Multi-Layer Perceptron (MLP) for Q-value approximation."""
    def __init__(self, input_dim, output_dim):
        super(DQN, self).__init__()
        self.fc1 = nn.Linear(input_dim, 128)
        self.fc2 = nn.Linear(128, 128)
        self.fc3 = nn.Linear(128, output_dim)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)